#!/usr/bin/env bash
#set Nginx to listen on port 80

#remove existing file
rm /etc/nginx/sites-enabled/default

#link default file in sites-availabe with sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
